# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Windows Server Core image with PowerShell
FROM mcr.microsoft.com/powershell:lts-nanoserver-1809

# Set the working directory
WORKDIR /app

# Copy PowerShell profile scripts into the container
COPY Microsoft.PowerShell_profile.ps1 /app/
COPY setup.ps1 /app/

# Execute the setup script to install the profile
RUN pwsh -Command "& {Start-Process pwsh -ArgumentList '-NoProfile -File setup.ps1' -Verb RunAs}"

# The default command to run PowerShell
CMD ["pwsh"]
